import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import FooterBar from "@/components/FootBar";
import AuthModal from "@/components/AuthModel";
import CartSidebar from "@/components/CartSideBar";
import { ModalProvider } from "@/context/ModalContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Preetizen",
  description: "Generated by Sreejita Sen",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ModalProvider>
          <Navbar />
          {children}
          <FooterBar />
          <AuthModal />
          <CartSidebar/>
        </ModalProvider>
      </body>
    </html>
  );
}
